CREATE TABLE IF NOT EXISTS users (
	id BIGINT PRIMARY KEY,
	locale TEXT NOT NULL DEFAULT 'en_US',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_spam_reports (
	id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
	victim BIGINT NOT NULL,
	attacker BIGINT NOT NULL,
	reason TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (victim) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (attacker) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guilds (
	id BIGINT PRIMARY KEY,
	locale TEXT NOT NULL DEFAULT 'en_US',
	welcome_channel BIGINT,
	log_channel BIGINT
);


